Update platform.json
WallaceWilliam to rahuldeo2047
credit: WallaceWilliam

Have to do it due to 

PackageManager: Installing framework-esp8266-rtos-sdk-idf-platformio @ >=1.0.2
Downloading...
Warning! Package Mirror: The 'sha1' sum 'be44a499f377f86fd600e1e1963b5ef7a36c2146' of downloaded file 'framework-esp8266-rtos-sdk-idf-platformio-master.zip' is not equal to remote 'd7acb3df7da6ec7147c00d9a9b00bbc186692f61'
Looking for another mirror...
Error: Could not install 'framework-esp8266-rtos-sdk-idf-platformio' with version requirements '>=1.0.2' for your system 'linux_x86_64'.

Please try this solution -> http://bit.ly/faq-package-manager